name: source_server
description: A dart implementation of Source's Query Protocol and RCON from the developer.valvesoftware.com wiki.
version: 3.2.0-dev
homepage: https://github.com/Hexer10/source_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^0.14.2
  logging: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.5
  freezed: ^0.14.2
  lint: ^1.5.3
  test: ^1.17.8
