name: SourceServer
description: A library to connect to Source Dedicate Servers like CS:GO, CSS, TF2, ...
version: 0.0.1
author: Mattia <hexexer504@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'