name: source_server
description: A dart implementation of Source's Query Protocol and RCON.
version: 1.0.4
homepage: https://github.com/Hexer10/source_query_rcon
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2
  pedantic: ^1.5.0
